import { PinClass } from '../Classes/Pin_class';

export const pins = [
    new PinClass(0, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 1", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(0, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 2", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(0, "https://i0.wp.com/photofocus.com/wp-content/uploads/2019/03/jpegminifeaturedimage.jpg?fit=1920%2C1080&ssl=1", "Pin 3", "The pin that will become a history", ["kakadoo"], new Date()),
    new PinClass(0, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 4", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(0, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 5", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(0, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 6", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(0, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 7", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(0, "https://i.pinimg.com/736x/28/2c/d7/282cd7c9f3a1f7a6ce9d0b7fe5c76009.jpg", "Pin 8", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(0, "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu_fpPmbK-bebEeX036y7frmW06amtCkG1ew&usqp=CAU", "Pin 9", "The pin that will become a history", ["kakadoo"], new Date()),
    new PinClass(0, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 10", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(0, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 11", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(0, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 12", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(0, "https://images.ctfassets.net/hrltx12pl8hq/7yQR5uJhwEkRfjwMFJ7bUK/dc52a0913e8ff8b5c276177890eb0129/offset_comp_772626-opt.jpg?fit=fill&w=800&h=300", "Pin 13", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(0, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 14", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(0, "https://media.istockphoto.com/id/1322277517/photo/wild-grass-in-the-mountains-at-sunset.jpg?s=612x612&w=0&k=20&c=6mItwwFFGqKNKEAzv0mv6TaxhLN3zSE43bWmFN--J5w=", "Pin 15", "The pin that will become a history", ["life", "world"], new Date()),
  
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 16", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 17", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 18", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(1, "https://pixlr.com/images/index/hero.webp", "Pin 19", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 20", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 21", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 22", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 23", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 24", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 25", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 26", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 27", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 28", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 29", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 30", "The pin that will become a history", ["sky", "bottom"], new Date()),
    
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 31", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 32", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 33", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 34", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 35", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 36", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 37", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 38", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 39", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 40", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 41", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 42", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 43", "The pin that will become a history", ["life", "world"], new Date()),
    
]