import { PinClass } from '../Classes/Pin_class';

export const pins = [
    new PinClass(0, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 1", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(0, "https://images.pexels.com/photos/268533/pexels-photo-268533.jpeg?cs=srgb&dl=pexels-pixabay-268533.jpg&fm=jpg", "Pin2", "The pin that will become a history", ["tree"], new Date()),
    new PinClass(0, "https://i0.wp.com/photofocus.com/wp-content/uploads/2019/03/jpegminifeaturedimage.jpg?fit=1920%2C1080&ssl=1", "Pin 3", "The pin that will become a history", ["kakadoo"], new Date()),
    new PinClass(0, "https://watermark.lovepik.com/photo/20211119/large/lovepik-water-tree-picture_500280343.jpg", "Pin 4", "The pin that will become a history", ["tree"], new Date()),
    new PinClass(0, "https://ghantee.com/wp-content/uploads/2022/08/most-beautiful-trishul-image-on-the-internet-today-576x1024.jpg", "Pin 5", "The pin that will become a history", ["moon"], new Date()),
    new PinClass(0, "https://www.bhaktiphotos.com/wp-content/uploads/2018/04/Hindu-Shiva-God-Wallpaper-Free-Download.jpg", "Pin 6", "The pin that will become a history", ["buddha"], new Date()),
    new PinClass(0, "https://funkylife.in/wp-content/uploads/2022/09/good-night-image-from-funkylife-328.jpg", "Pin 7", "The pin that will become a history", ["goodnight"], new Date()),
    new PinClass(0, "https://i.pinimg.com/736x/28/2c/d7/282cd7c9f3a1f7a6ce9d0b7fe5c76009.jpg", "Pin 8", "The pin that will become a history", ["feather"], new Date()),
    new PinClass(0, "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu_fpPmbK-bebEeX036y7frmW06amtCkG1ew&usqp=CAU", "Pin 9", "The pin that will become a history", ["kakadoo"], new Date()),
    new PinClass(0, "https://imgd.aeplcdn.com/310x174/n/cw/ec/44686/activa-6g-right-front-three-quarter.jpeg?q=75", "Pin 10", "The pin that will become a history", ["moto"], new Date()),
    new PinClass(0, "https://ichef.bbci.co.uk/news/976/cpsprodpb/1572B/production/_88615878_976x1024n0037151.jpg", "Pin 11", "The pin that will become a history", ["hands"], new Date()),
    new PinClass(0, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 12", "The pin that will become a history", ["pineapple"], new Date()),
    new PinClass(0, "https://images.ctfassets.net/hrltx12pl8hq/7yQR5uJhwEkRfjwMFJ7bUK/dc52a0913e8ff8b5c276177890eb0129/offset_comp_772626-opt.jpg?fit=fill&w=800&h=300", "Pin 13", "The pin that will become a history", ["human", "photo"], new Date()),
    new PinClass(0, "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.dreamstime.com%2Fphotos-images%2Fnature.html&psig=AOvVaw1--AVus6DhVR5NihZSY6eQ&ust=1669363035674000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCIjHxLS0xvsCFQAAAAAdAAAAABAx", "Pin 14", "The pin that will become a history", ["forest"], new Date()),
    new PinClass(0, "https://media.istockphoto.com/id/1322277517/photo/wild-grass-in-the-mountains-at-sunset.jpg?s=612x612&w=0&k=20&c=6mItwwFFGqKNKEAzv0mv6TaxhLN3zSE43bWmFN--J5w=", "Pin 15", "The pin that will become a history", ["sunset"], new Date()),
  
    new PinClass(1, "https://watermark.lovepik.com/photo/20211119/large/lovepik-water-tree-picture_500280343.jpg", "Pin 16", "The pin that will become a history", ["tree"], new Date()),
    new PinClass(1, "https://media.istockphoto.com/id/1322277517/photo/wild-grass-in-the-mountains-at-sunset.jpg?s=612x612&w=0&k=20&c=6mItwwFFGqKNKEAzv0mv6TaxhLN3zSE43bWmFN--J5w=", "Pin 17", "The pin that will become a history", ["sunset"], new Date()),
    new PinClass(1, "https://media.istockphoto.com/id/517188688/photo/mountain-landscape.jpg?s=612x612&w=0&k=20&c=A63koPKaCyIwQWOTFBRWXj_PwCrR4cEoOw2S9Q7yVl8=", "Pin 18", "The pin that will become a history", ["sunset"], new Date()),
    new PinClass(1, "https://pixlr.com/images/index/hero.webp", "Pin 19", "The pin that will become a history", ["hero"], new Date()),
    new PinClass(1, "https://images.unsplash.com/photo-1498932042873-e35fb6535a02?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHw%3D&w=1000&q=80", "Pin 20", "The pin that will become a history", ["sunset"], new Date()),
    new PinClass(1, "https://images.unsplash.com/photo-1500817487388-039e623edc21?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHw%3D&w=1000&q=80", "Pin 21", "The pin that will become a history", ["mountains"], new Date()),
    new PinClass(1, "https://upload.wikimedia.org/wikipedia/commons/7/74/%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg", "Pin 22", "The pin that will become a history", ["pineapple"], new Date()),
    new PinClass(1, "https://images.unsplash.com/photo-1523205221523-4ea4a686d5ab?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE4fHx8ZW58MHx8fHw%3D&w=1000&q=80", "Pin 23", "The pin that will become a history", ["mountains"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 24", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(1, "https://www.supercars.net/blog/wp-content/uploads/2022/09/Best-New-Sports-and-Performance-Cars-2022_Chevrolet_Corvette.jpg", "Pin 25", "The pin that will become a history", ["sportscar", "corvette"], new Date()),
    new PinClass(1, "https://cfx-wp-images.imgix.net/2019/10/2020-Chevrolet-Corvette-Stingray.jpg?auto=compress%2Cformat&fit=scale&h=683&ixlib=php-3.3.0&w=1024&wpsize=large&s=372dd890c62af0ce45c028a5ce58aa4b", "Pin 26", "The pin that will become a history", ["corvette"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 27", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(1, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 28", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(1, "https://images.unsplash.com/photo-1628519592419-bf288f08cef5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fHNwb3J0cyUyMGNhcnxlbnwwfHwwfHw%3D&w=1000&q=80", "Pin 29", "The pin that will become a history", ["lambordghini"], new Date()),
    new PinClass(1, "https://carsalesbase.com/wp-content/uploads/2020/07/US-sports-car-sales-Chevrolet_Corvette.jpg", "Pin 30", "The pin that will become a history", ["corvette"], new Date()),
    
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 31", "The pin that will become a history", ["life", "world"], new Date()),
    new PinClass(2, "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/screen-shot-2020-11-13-at-12-18-46-pm-1605287983.png?crop=0.700xw:0.840xh;0.151xw,0&resize=1200:*", "Pin 32", "The pin that will become a history", ["ferrari"], new Date()),
    new PinClass(2, "https://www.skylineuniversity.ac.ae/blog/images/2021/01/08/isvsit.jpg", "Pin 33", "The pin that will become a history", ["informaton"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 34", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(2, "https://www.ecpi.edu/sites/default/files/MS%20Tech%20Sept%2025.png", "Pin 35", "The pin that will become a history", ["information"], new Date()),
    new PinClass(2, "https://images.indianexpress.com/2022/06/india-Football-pic-credit-aiff.jpg", "Pin 36", "The pin that will become a history", ["football"], new Date()),
    new PinClass(2, "https://www.ecpi.edu/sites/default/files/infosys_3.png", "Pin 37", "The pin that will become a history", ["information", "brain"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 38", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(2, "https://valdiviajovani.files.wordpress.com/2013/02/motivation.png", "Pin 39", "The pin that will become a history", ["sports", "motivation"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 40", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(2, "https://sasasemeredi.files.wordpress.com/2021/01/maxresdefault.jpg?w=1280", "Pin 41", "The pin that will become a history", ["motivation"], new Date()),
    new PinClass(2, "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg", "Pin 42", "The pin that will become a history", ["sky", "bottom"], new Date()),
    new PinClass(2, "https://img.olympicchannel.com/images/image/private/t_social_share_thumb/f_auto/primary/qjxgsf7pqdmyqzsptxju", "Pin 43", "The pin that will become a history", ["football"], new Date()),
    
]