/*---App---*/
export const SHOW_MORE_PINS = "SHOW_MORE_PINS";
export const RESET_SHOWED_PINS_COUNT = "RESET_SHOWED_PINS_COUNT";

export const UPDATE_PINS_LIST = "UPDATE_PINS_LIST";
export const FORCE_UPDATE = "FORCE_UPDATE";
export const SEARCH_PINS = "SEARCH_PINS";
export const FILTER_PINS_BASED_ON_USER_PREFERENCES = "FILTER_PINS_BASED_ON_USER_PREFERENCES";
export const SHOW_RECENT_PINS = "SHOW_RECENT_PINS";

/*---User---*/
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SIGN_UP = "SIGN_UP";

export const EDIT_PROFILE = "EDIT_PROFILE";

export const CREATE_PIN = "CREATE_PIN";
export const EDIT_PIN = "EDIT_PIN";
export const DELETE_PIN = "DELETE_PIN";
export const SAVE_PIN = "SAVE_PIN";
export const DELETE_PIN_FROM_SAVED = "DELETE_PIN_FROM_SAVED";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const FOLLOW = "FOLLOW";
export const UNFOLLOW = "UNFOLLOW";

export const UPDATE_TAGS_VIEW_FREQUENCY_HISTOGRAM = "UPDATE_TAGS_VIEW_FREQUENCY_HISTOGRAM";

/*---Search---*/
export const CHANGE_PINS_SEARCH_TERM = "CHANGE_PINS_SEARCH_TERM";
export const CHANGE_PINS_SORT_CRITERIA = "CHANGE_PINS_SEARCH_SORT_CRITERIA";

export const CHANGE_USER_PINS_SEARCH_TERM = "CHANGE_USER_PINS_SEARCH_TERM";
export const CHANGE_USER_PINS_SORT_CRITERIA = "CHANGE_USER_PINS_SEARCH_CRITERIA";

export const CHANGE_CONVERSATIONS_SEARCH_TERM = "CHANGE_CONVERSATIONS_SEARCH_TERM";

/*---Authorization---*/
export const OPEN_LOGIN_WINDOW = "OPEN_LOGIN_WINDOW";
export const OPEN_SIGN_UP_WINDOW = "OPEN_SIGN_UP_WINDOW";
export const CLOSE_AUTHORIZATION_WINDOW = "CLOSE_AUTHORIZATION_WINDOW";


/*---Show Message---*/
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";

/*---Confirmation---*/
export const CONFIRM_ACTION = "CONFIRM_ACTION";
export const CANCEL_CONFIRMATION = "CANCEL_CONFIRMATION";
export const SET_CONFIRMATION_VALUES = "SET_CONFIRMATION_VALUES";