/*---User---*/
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";

/*---Search---*/
export const CHANGE_PINS_SEARCH_TERM = "CHANGE_PINS_SEARCH_TERM";
export const CHANGE_CONVERSATIONS_SEARCH_TERM = "CHANGE_CONVERSATIONS_SEARCH_TERM";