/*---User---*/
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";

export const CREATE_PIN = "CREATE_PIN";
export const EDIT_PIN = "EDIT_PIN";
export const DELETE_PIN = "DELETE_PIN";


/*---Search---*/
export const CHANGE_PINS_SEARCH_TERM = "CHANGE_PINS_SEARCH_TERM";
export const CHANGE_PINS_SORT_CRITERIA = "CHANGE_PINS_SEARCH_SORT_CRITERIA";

export const CHANGE_CONVERSATIONS_SEARCH_TERM = "CHANGE_CONVERSATIONS_SEARCH_TERM";
export const CHANGE_CONVERSATIONS_SORT_CRITERIA = "CHANGE_CONVERSATIONS_SEARCH_SORT_CRITERIA";

export const CHANGE_USER_PINS_SEARCH_TERM = "CHANGE_USER_PINS_SEARCH_TERM";
export const CHANGE_USER_PINS_SORT_CRITERIA = "CHANGE_USER_PINS_SEARCH_CRITERIA";